version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - wanderer-api
  wanderer-api:
    image: armlfs/wanderer-api
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  mysql:
    external:
      name: armlfslocal_mysql
