version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - wanderer-api
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - ./env/mysql.env
  wanderer-api:
    image: armlfs/wanderer-api
    volumes:
      - ./env/wanderer-api.env:/mnt/.env
volumes:
  mysql:
    external:
      name: armlfs_mysql
