version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  mysql:
    external:
      name: armlfslocal_mysql
